-- AlterTable
ALTER TABLE "BookingPassenger" ADD COLUMN IF NOT EXISTS "seatOutbound" TEXT NOT NULL DEFAULT '';
ALTER TABLE "BookingPassenger" ADD COLUMN IF NOT EXISTS "seatReturn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "BookingPassenger" ADD COLUMN IF NOT EXISTS "seatFeeCents" INTEGER NOT NULL DEFAULT 0;
