-- AlterTable
ALTER TABLE "PriceQuote" ADD COLUMN IF NOT EXISTS "specialAssistance" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "specialAssistance" JSONB NOT NULL DEFAULT '{}';
