-- AlterTable
ALTER TABLE "PriceQuote" ADD COLUMN "adultCount" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "PriceQuote" ADD COLUMN "childCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PriceQuote" ADD COLUMN "infantCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PriceQuote" ADD COLUMN "unitAdultFareCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PriceQuote" ADD COLUMN "travellersDraft" JSONB NOT NULL DEFAULT '[]';
